clone:
  git:
    image: bash
    settings:
      lfs: false

labels:
  backend: local

steps:
  - name: build-frontend
    image: bash
    commands:
      - export PATH="/home/diama/.nvm/versions/node/v24.16.0/bin:$PATH"
      - cd frontend
      - npm install
      - npm run build

  - name: build-backend
    image: bash
    commands:
      - export PATH="/usr/local/go/bin:$PATH"
      - cd backend
      - rm -rf cmd/server/dist
      - cp -r ../frontend/dist cmd/server/dist
      - go mod tidy
      - go build -o aeris-server ./cmd/server

when:
  event: push
  branch: main